
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author teo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        commentsAboutTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        genderCombobox = new javax.swing.JComboBox();
        findButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        howOftenCombobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeCombobox = new javax.swing.JComboBox();
        aboutButton = new javax.swing.JButton();
        aerobics = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentsAerobicsTextArea = new javax.swing.JTextArea();
        commentAerobicsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        upperLower = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        commentsFullTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        commentFullButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        weights3TimesMen = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        commentsWeights1TextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        commentWeights1Button = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        weights4TimesMen = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        commentsWeights2TextArea = new javax.swing.JTextArea();
        commentWeights2Button = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        weights4TimesWomen = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        commentsWomenTextArea = new javax.swing.JTextArea();
        commentWomenButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        about = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        commentsAboutTextArea = new javax.swing.JTextArea();
        homerPhoto = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        tabs.setBackground(new java.awt.Color(198, 211, 255));
        tabs.setForeground(new java.awt.Color(51, 51, 255));
        tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabs.setPreferredSize(new java.awt.Dimension(1000, 600));

        Menu.setBackground(new java.awt.Color(166, 187, 255));
        Menu.setForeground(new java.awt.Color(255, 236, 201));
        Menu.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Επιλέξτε τα στοιχεία που σας ταιριάζουν και θα βρούμε το ιδανικό πρόγραμμα γυμναστικής για εσάς");

        genderCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female"}));

        findButton.setText("ΒΡΕΣ ΜΟΥ ΠΡΟΓΡΑΜΜΑ");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Επιλέξτε το φύλο σας");

        howOftenCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        howOftenCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howOftenComboboxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Επιλέξτε πόσο συχνά θα προπονήστε μέσα στην εβδομάδα");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Επιλέξτε μεταξύ αερόβιου ή βαρών");

        typeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aerobics", "Weights"}));

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(genderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(howOftenCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(genderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(howOftenCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(typeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        tabs.addTab("Main Menu", Menu);

        aerobics.setBackground(new java.awt.Color(166, 187, 255));
        aerobics.setPreferredSize(new java.awt.Dimension(1000, 600));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Διάδρομος", "20'"},
                {"2", "Ποδήλατο", "20'"},
                {"3", "Κάμψεις ", "4 σετ των 15 "},
                {"4", "Κοιλιακοούς", "4 σετ των 20"},
                {"5", "Πλάγιους Κοιλιακούς", "4 σετ των 15"},
                {"6", "Stretching", "15'"},
                {"7", "Περπάτημα", "15'"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων ή χρόνος"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        commentsAerobicsTextArea.setColumns(20);
        commentsAerobicsTextArea.setRows(5);
        jScrollPane2.setViewportView(commentsAerobicsTextArea);

        commentAerobicsButton.setText("ΑΠΟΘΗΚΕΥΣΗ ΣΧΟΛΙΟΥ");
        commentAerobicsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentAerobicsButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Σχόλια για το ασκησολόγιο");

        javax.swing.GroupLayout aerobicsLayout = new javax.swing.GroupLayout(aerobics);
        aerobics.setLayout(aerobicsLayout);
        aerobicsLayout.setHorizontalGroup(
            aerobicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aerobicsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(aerobicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentAerobicsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        aerobicsLayout.setVerticalGroup(
            aerobicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aerobicsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(aerobicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(aerobicsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addComponent(commentAerobicsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        tabs.addTab("Aerobics", aerobics);

        upperLower.setBackground(new java.awt.Color(166, 187, 255));
        upperLower.setPreferredSize(new java.awt.Dimension(1000, 600));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Έλξεις ανοιχτές", "4 σετ των 12"},
                {"2", "Κοπηλατική", "4 σετ των 8"},
                {"3", "Πάγκο οριζόντια", "4 σετ των 8"},
                {"4", "Πάγκο με κλίση", "4 σετ των 8"},
                {"5", "Αλτήρες δικέφαλα", "4 σετ των 12"},
                {"6", "Γαλλικές τρικέφαλα", "4 σετ των 10"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        commentsFullTextArea.setColumns(20);
        commentsFullTextArea.setRows(5);
        jScrollPane4.setViewportView(commentsFullTextArea);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Σχόλια για το ασκησολόγιο");

        commentFullButton.setText("ΑΠΟΘΗΚΕΥΣΗ ΣΧΟΛΙΟΥ");
        commentFullButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentFullButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Για το πάνω μέρος του σώματος");

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Καθίσματα ", "4 σετ των 12"},
                {"2", "Deadlifts", "4 σετ των 8"},
                {"3", "Εκτάσεις ποδιών", "4 σετ των 8"},
                {"4", "Κάμψεις δικεφάλου ποδιού", "4 σετ των 8"},
                {"5", "Πιέσεις γαμπών", "4 σετ των 12"},
                {"6", "Ανοίγματα με αλτήρες", "4 σετ των 10"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Για το κάτω μέρος του σώματος");

        javax.swing.GroupLayout upperLowerLayout = new javax.swing.GroupLayout(upperLower);
        upperLower.setLayout(upperLowerLayout);
        upperLowerLayout.setHorizontalGroup(
            upperLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperLowerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(upperLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(upperLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentFullButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        upperLowerLayout.setVerticalGroup(
            upperLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperLowerLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(upperLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(upperLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperLowerLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(commentFullButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(upperLowerLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tabs.addTab("Upper/Lower Body", upperLower);

        weights3TimesMen.setBackground(new java.awt.Color(166, 187, 255));

        commentsWeights1TextArea.setColumns(20);
        commentsWeights1TextArea.setRows(5);
        jScrollPane6.setViewportView(commentsWeights1TextArea);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Σχόλια για το ασκησολόγιο");

        commentWeights1Button.setText("ΑΠΟΘΗΚΕΥΣΗ ΣΧΟΛΙΟΥ");
        commentWeights1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentWeights1ButtonActionPerformed(evt);
            }
        });

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Κάμψεις", "4 σετ των 12"},
                {"2", "Πάγκος οριζόντια", "4 σετ των 8"},
                {"3", "Πάγκος με κλίση", "4 σετ των 8"},
                {"4", "Αλτήρες ανοίγματα", "4 σετ των 8"},
                {"5", "Σχοινιά τρικέφαλα", "4 σετ των 10"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane10.setViewportView(jTable4);

        jTable5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Καθίσματα", "4 σετ των 12"},
                {"2", "Deadlifts", "4 σετ των 8"},
                {"3", "Ανοίγματα τετρακέφαλους", "4 σετ των 8"},
                {"4", "Κάμψεις δικεφάλων ποδιών", "4 σετ των 8"},
                {"5", "Πιέσεις όμων", "4 σετ των 12"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane11.setViewportView(jTable5);

        jTable6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Έλξεις ανοιχτές", "4 σετ των 12"},
                {"2", "Κοπηλατική", "4 σετ των 8"},
                {"3", "Έλξεις σε μηχάνημα", "4 σετ των 8"},
                {"4", "Αλτήρες με κλίση", "4 σετ των 8"},
                {"5", "Αλτήρες δικέφαλα", "4 σετ των 8"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane12.setViewportView(jTable6);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Για όσους θα γυμναστούν 3 φορές την εβδομάδα");

        javax.swing.GroupLayout weights3TimesMenLayout = new javax.swing.GroupLayout(weights3TimesMen);
        weights3TimesMen.setLayout(weights3TimesMenLayout);
        weights3TimesMenLayout.setHorizontalGroup(
            weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weights3TimesMenLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(weights3TimesMenLayout.createSequentialGroup()
                        .addGroup(weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(41, 41, 41)
                        .addGroup(weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentWeights1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        weights3TimesMenLayout.setVerticalGroup(
            weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weights3TimesMenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(weights3TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weights3TimesMenLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(commentWeights1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(weights3TimesMenLayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabs.addTab("Weights Men 1", weights3TimesMen);

        weights4TimesMen.setBackground(new java.awt.Color(166, 187, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Σχόλια για το ασκησολόγιο");

        commentsWeights2TextArea.setColumns(20);
        commentsWeights2TextArea.setRows(5);
        jScrollPane7.setViewportView(commentsWeights2TextArea);

        commentWeights2Button.setText("ΑΠΟΘΗΚΕΥΣΗ ΣΧΟΛΙΟΥ");
        commentWeights2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentWeights2ButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Για όσους θα γυμναστούν 4 φορές την εβδομάδα");

        jTable7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Έλξεις ανοιχτές", "4 σετ των 12"},
                {"2", "Κοπηλατική", "4 σετ των 8"},
                {"3", "Έλξεις σε μηχάνημα", "4 σετ των 8"},
                {"4", "Αλτήρες με κλίση", "4 σετ των 8"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane13.setViewportView(jTable7);

        jTable8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Αλτήρες δικέφαλα", "4 σετ των 10"},
                {"2", "Σχοινιά τρικέφαλα", "4 σετ των 10"},
                {"3", "Στραβόμπαρα", "4 σετ των 10"},
                {"4", "Γαλλικές", "4 σετ των 10"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane14.setViewportView(jTable8);

        jTable9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Καθίσματα", "4 σετ των 12"},
                {"2", "Deadlifts", "4 σετ των 8"},
                {"3", "Ανοίγματα τετρακέφαλους", "4 σετ των 8"},
                {"4", "Κάμψεις δικεφάλων ποδιών", "4 σετ των 8"},
                {"5", "Πιέσεις όμων", "4 σετ των 12"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane15.setViewportView(jTable9);

        jTable10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Κάμψεις", "4 σετ των 12"},
                {"2", "Πάγκος οριζόντια", "4 σετ των 8"},
                {"3", "Πάγκος με κλίση", "4 σετ των 8"},
                {"4", "Αλτήρες ανοίγματα", "4 σετ των 8"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane16.setViewportView(jTable10);

        javax.swing.GroupLayout weights4TimesMenLayout = new javax.swing.GroupLayout(weights4TimesMen);
        weights4TimesMen.setLayout(weights4TimesMenLayout);
        weights4TimesMenLayout.setHorizontalGroup(
            weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weights4TimesMenLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(commentWeights2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        weights4TimesMenLayout.setVerticalGroup(
            weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weights4TimesMenLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(11, 11, 11)
                .addGroup(weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weights4TimesMenLayout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(weights4TimesMenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentWeights2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tabs.addTab("Weights Men 2", weights4TimesMen);

        weights4TimesWomen.setBackground(new java.awt.Color(166, 187, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Σχόλια για το ασκησολόγιο");

        commentsWomenTextArea.setColumns(20);
        commentsWomenTextArea.setRows(5);
        jScrollPane8.setViewportView(commentsWomenTextArea);

        commentWomenButton.setText("ΑΠΟΘΗΚΕΥΣΗ ΣΧΟΛΙΟΥ");
        commentWomenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentWomenButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Για όσες θα γυμναστούν 4 φορές την εβδομάδα");

        jTable11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Έλξεις ανοιχτές", "4 σετ των 10"},
                {"2", "Κοπηλατική", "4 σετ των 6"},
                {"3", "Έλξεις σε μηχάνημα", "4 σετ των 6"},
                {"4", "Αλτήρες με κλίση", "4 σετ των 6"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane17.setViewportView(jTable11);

        jTable12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Κάμψεις", "4 σετ των 10"},
                {"2", "Πάγκος οριζόντια", "4 σετ των 6"},
                {"3", "Πάγκος με κλίση", "4 σετ των 6"},
                {"4", "Αλτήρες ανοίγματα", "4 σετ των 8"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane18.setViewportView(jTable12);

        jTable13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Αλτήρες δικέφαλα", "4 σετ των 8"},
                {"2", "Σχοινιά τρικέφαλα", "4 σετ των 8"},
                {"3", "Στραβόμπαρα", "4 σετ των 8"},
                {"4", "Γαλλικές", "4 σετ των 8"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane19.setViewportView(jTable13);

        jTable14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Καθίσματα", "4 σετ των 10"},
                {"2", "Deadlifts", "4 σετ των 6"},
                {"3", "Ανοίγματα τετρακέφαλους", "4 σετ των 6"},
                {"4", "Κάμψεις δικεφάλων ποδιών", "4 σετ των 6"},
                {"5", "Πιέσεις όμων", "4 σετ των 10"}
            },
            new String [] {
                "Αριθμός άσκησης", "Όνομα άσκησης", "Αριθμός επαναλήψεων "
            }
        ));
        jScrollPane20.setViewportView(jTable14);

        javax.swing.GroupLayout weights4TimesWomenLayout = new javax.swing.GroupLayout(weights4TimesWomen);
        weights4TimesWomen.setLayout(weights4TimesWomenLayout);
        weights4TimesWomenLayout.setHorizontalGroup(
            weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weights4TimesWomenLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentWomenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(41, 41, 41))
        );
        weights4TimesWomenLayout.setVerticalGroup(
            weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weights4TimesWomenLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weights4TimesWomenLayout.createSequentialGroup()
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(weights4TimesWomenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentWomenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tabs.addTab("Weights Women", weights4TimesWomen);

        about.setBackground(new java.awt.Color(166, 187, 255));

        commentsAboutTextArea.setColumns(20);
        commentsAboutTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commentsAboutTextArea.setRows(5);
        commentsAboutTextArea.setText("Ονομάζομαι Μαστρομανώλης Θεόδωρος , είμαι 19 ετών και ανέπτυξα\nτη συγκεκριμένη εφαρμογή στα πλαίσια του μαθήματος \"Αλληλεπίδραση\nΑνθρώπου-Μηχανής\" , του 3ου εξαμήνου των σπουδών μου. Στη συγκε-\nκριμένη εφαρμογή , τα προγράμματα γυμναστικής που χρησιμοποίησα \nτα πήρα από την ιστοσελίδα : https://www.examplepage.com . Αν έχετε\nπεραιτέρω απορίες σχετικά με τη χρήση της εφαρμογής , ή έχετε βρει\nκάτι που δε δουλεύει σωστά μέσα σε αυτή , θα σας παρακαλούσα να \nεπικοινωνήσετε μαζί μου στο teomastro1999@gmail.com , έτσι ώστε να \nεπιλύσω το πρόβλημα όσο το δυνατόν γίνεται πιο γρήγορα.");
        jScrollPane9.setViewportView(commentsAboutTextArea);

        homerPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homer.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Μία φωτογραφία μου");

        menuButton.setText("ΕΠΙΣΤΡΟΦΗ ΣΤΟ ΜΕΝΟΥ");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about);
        about.setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addComponent(homerPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homerPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );

        tabs.addTab("About", about);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commentAerobicsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentAerobicsButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Το σχόλιό σας αποθηκεύτηκε");
        commentsAerobicsTextArea.setText("");
    }//GEN-LAST:event_commentAerobicsButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        tabs.setSelectedIndex(6);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void howOftenComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howOftenComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_howOftenComboboxActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        if(howOftenCombobox.getSelectedItem().equals("1")&&typeCombobox.getSelectedItem().equals("Weights")){
            tabs.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null,"Θα κάνετε υποχρεωτικά αερόβιο επειδή επιλέξατε 1 προπόνηση την εβδομάδα");
        }
        else if(typeCombobox.getSelectedItem().equals("Aerobics")){
            tabs.setSelectedIndex(1);
        }
        else if(typeCombobox.getSelectedItem().equals("Weights")&&howOftenCombobox.getSelectedItem().equals("1")||howOftenCombobox.getSelectedItem().equals("2")){
            tabs.setSelectedIndex(2);
        }
        else if(typeCombobox.getSelectedItem().equals("Weights")&&howOftenCombobox.getSelectedItem().equals("3")&&genderCombobox.getSelectedItem().equals("Male")){
            tabs.setSelectedIndex(3);
        }
        else if(typeCombobox.getSelectedItem().equals("Weights")&&howOftenCombobox.getSelectedItem().equals("4")&&genderCombobox.getSelectedItem().equals("Male")){
            tabs.setSelectedIndex(4);
        }
        else if(typeCombobox.getSelectedItem().equals("Weights")&&howOftenCombobox.getSelectedItem().equals("4")&&genderCombobox.getSelectedItem().equals("Female")){
            tabs.setSelectedIndex(5);
        }
        else if(typeCombobox.getSelectedItem().equals("Weights")&&howOftenCombobox.getSelectedItem().equals("1")&&genderCombobox.getSelectedItem().equals("Female")){
            tabs.setSelectedIndex(2);
        }
        else if(typeCombobox.getSelectedItem().equals("Weights")&&howOftenCombobox.getSelectedItem().equals("3")&&genderCombobox.getSelectedItem().equals("Female")){
            tabs.setSelectedIndex(2);
        }

    }//GEN-LAST:event_findButtonActionPerformed

    private void commentFullButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentFullButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Το σχόλιό σας αποθηκεύτηκε");
        commentsFullTextArea.setText("");
    }//GEN-LAST:event_commentFullButtonActionPerformed

    private void commentWeights1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentWeights1ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Το σχόλιό σας αποθηκεύτηκε");
        commentsWeights1TextArea.setText("");
    }//GEN-LAST:event_commentWeights1ButtonActionPerformed

    private void commentWeights2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentWeights2ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Το σχόλιό σας αποθηκεύτηκε");
        commentsWeights2TextArea.setText("");
    }//GEN-LAST:event_commentWeights2ButtonActionPerformed

    private void commentWomenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentWomenButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Το σχόλιό σας αποθηκεύτηκε");
        commentsWomenTextArea.setText("");
    }//GEN-LAST:event_commentWomenButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_menuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    //21 , μεγαλυτερο-μικροτερο , ζαρια , πέτρα/ψαλίδι/χαρτί 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel about;
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel aerobics;
    private javax.swing.JButton commentAerobicsButton;
    private javax.swing.JButton commentFullButton;
    private javax.swing.JButton commentWeights1Button;
    private javax.swing.JButton commentWeights2Button;
    private javax.swing.JButton commentWomenButton;
    private javax.swing.JTextArea commentsAboutTextArea;
    private javax.swing.JTextArea commentsAerobicsTextArea;
    private javax.swing.JTextArea commentsFullTextArea;
    private javax.swing.JTextArea commentsWeights1TextArea;
    private javax.swing.JTextArea commentsWeights2TextArea;
    private javax.swing.JTextArea commentsWomenTextArea;
    private javax.swing.JButton findButton;
    private javax.swing.JComboBox genderCombobox;
    private javax.swing.JLabel homerPhoto;
    private javax.swing.JComboBox howOftenCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JButton menuButton;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JComboBox typeCombobox;
    private javax.swing.JPanel upperLower;
    private javax.swing.JPanel weights3TimesMen;
    private javax.swing.JPanel weights4TimesMen;
    private javax.swing.JPanel weights4TimesWomen;
    // End of variables declaration//GEN-END:variables
}
